services:
  # ----------------- Database Service -----------------
  - type: pserv
    name: sneh-ai-db
    plan: free
    database: postgres

  # ----------------- Web Service -----------------
  - type: web
    name: sneh-ai-backend
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: sneh-ai-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: "HS256"
