services:
  # ----------------- Database Service -----------------
  - type: psql
    name: sneh-ai-db # You can give it a friendly name
    plan: free
    # postgresql_version: 15 # Optional, but good practice

  # ----------------- Web Service -----------------
  - type: web
    name: sneh-ai-backend
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: DATABASE_URL
        fromService:
          type: psql
          name: sneh-ai-db # This MUST match the database name above
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: "HS256"
      # --- IMPORTANT: Manually add other keys in Render Dashboard ---
      # BASE_URL, GEMINI_API_KEY, GCP_PROJECT_ID, etc.